### PR TITLE
Support large tables which don't fit in RAM

### LINKED ISSUE #1: Use Too Much Memory, Killed by System
I'm using this project to split the .sql file to make the pg_dump dumped file in an order that backup programs can deduplicate the existing data.
The dumped file is more than 1000GB, which is a kind of big. So I guess the data may be sorted in memory, so it's easy to use out.

### PR DESCRIPTION
**Pull request by akaihola**
Fixes #1

Use merge sort with temporary files to put a cap to memory usage.

### CODE REVIEW

**Comment by akaihola** [comment]
@oldcai could you try whether this branch
- sorts your large database without getting killed for using too much memory
- has acceptable performance

**Comment by akaihola** [comment]
@oldcai I've now finalized this fix. Would you accept my invitation as collaborator for this repository and review the pull request?

**Comment by oldcai** [comment]
> @oldcai I've now finalized this fix. Would you accept my invitation as collaborator for this repository and review the pull request?

Thank you for your efforts. I'm honoured to do that.
I'll review the code and do some manual tests.

**Comment by oldcai** [comment]
✅ I downloaded the code and ran it on my dev environment with some test data successfully.

⚠️ Python version requirement is too high. When I was trying to test it in the product environment, the minimal Python version requirement is 3.7 or even 3.8 when the other MR is merged, which is much higher than the CentOS stable version 3.6.8.

Then I removed the annotation code and successfully ran it.

I'm currently doing a benchmark on a 167G file and will continue reviewing the code after it finishes.

❓ Additionally, I found an interesting fact that although the memory limit is set to `10**8`, which should be 100M, the actual memory use and the temporary file sizes are just about 50MB. But I don't think it's an issue since the file count won't affect the performance of `heapq.merge` too much.

**Comment by akaihola** [comment]
> ✅ I downloaded the code and ran it on my dev environment with some test data successfully.

Good to hear that it works at least in a simple case!

> ⚠️ Python version requirement is too high. When I was trying to test it in the product environment, the minimal Python version requirement is 3.7 or even 3.8 when the other MR is merged, which is much higher than the CentOS stable version 3.6.8.

Ah, sorry about that. I'm trying to be a good Python community citizen and encourage upgrading from unsupported Python versions, but I do recognize that in RedHat/CentOS land the versions drag a bit behind... Would a Docker image help you?

> ❓ Additionally, I found an interesting fact that although the memory limit is set to `10**8`, which should be 100M, the actual memory use and the temporary file sizes are just about 50MB. But I don't think it's an issue since the file count won't affect the performance of [heapq.merge()](https://docs.python.org/3/library/heapq.html#heapq.merge) too much.

Interesting! Documentation for [sys.getsizeof()](https://docs.python.org/3/library/sys.html#sys.getsizeof) clearly says that it should return the size of objects in bytes. And this patch is counting both each string stored in the buffer as well as the overhead size of the buffer list object itself.

Are you going to experiment with different memory limits? Would it make sense to make the limit configurable by command line option?

**Review by oldcai — APPROVED** [review]
I believe the memory inaccuracy is due to the `sys.getsizeof` API and won't affect the performance too much.

I made a patch for the unstable sorting issue, and it needs your review @akaihola

**Comment by akaihola** [comment]
Thanks @oldcai, looks good! I changed the command line to use an optional `-m`/`--max-memory` argument, which also supports memory units like `k`, `mb`, `GiB` etc.

I rebased the commits a bit and force pushed.

**Review by oldcai — APPROVED** [review]
Nice implementation! Testing successfully on small data.

Thank you for your great work!

**Comment by oldcai** [comment]
I tested it with a 444G `.sql` file and it finished within `523m22.189s`.

The archive size of a full backup with compression is `64.585 GB`, while an incremental backup costs only `7.948 GB`, which is a significant reduction. @akaihola  Thank you for your excellent work!

**Comment by akaihola** [comment]
> I tested it with a 444G `.sql` file and it finished within `523m22.189s`.

I wonder how much performance we could squeeze out of Python with some tricks. It would also be interesting to look at how much running with [PyPy](https://www.pypy.org/) or compiling using [mypyc](https://github.com/mypyc/mypyc), [nuitka](https://nuitka.net/) or [Shed Skin](https://shedskin.github.io/), or even [Cython](https://cython.org/) could improve performance..

> The archive size of a full backup with compression is `64.585 GB`, while an incremental backup costs only `7.948 GB`, which is a significant reduction.

Cool! Could I mention this as an example in the README?

**Pull request merged**
